### ISSUE TITLE
Cry or laugh?

### ISSUE THREAD

**Issue by berezovskyi** [OSLC/oslc-browser#15]
Just ran npm install ([updated README](https://github.com/OSLC/oslc-browser/commit/e0358f9cba79dd2ac2742c8ed456193d7af7e86e), btw), got this:

```
added 1743 packages from 975 contributors and audited 1817 packages in 105.799s

20 packages are looking for funding
  run `npm fund` for details

found 2056 vulnerabilities (885 low, 18 moderate, 1152 high, 1 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
```

I am curious whether I shall laugh about 1743 deps or cry about 1152 high sec issues?

**Comment by jamsden** [comment]
Well, this is using React frameworks and IBM Carbon components, so I'd expect there to be lots of dependencies and lots of request for open source contribution. Also, its possible the dependencies are out of date and need to be updated. 

I don't think this browser works in its current state, haven't tried it in a while. I don't have any time to work on this, so we should consider it an in progress example or proof of concept rather than an active open source project.
